# Generated by Django 4.1.6 on 2023-02-09 01:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0004_alter_pet_sex"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="sex",
            field=models.CharField(
                choices=[
                    ("Female", "Female"),
                    ("Male", "Male"),
                    ("Not informed", "Default"),
                ],
                default="Not informed",
                max_length=20,
            ),
        ),
    ]
