# Generated by Django 4.1.6 on 2023-02-10 17:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("traits", "0002_trait_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trait",
            name="pets",
        ),
    ]
